CC = clang++


                                        all : prog

                                                  prog : $(OBJ) ${CC} $(OBJ)
                                                             $(LFLAGS) -
                                o $ @

                                    .cpp.o
    : ${CC} - g ${CFLAGS} - c $ <
                            -o $ @


              clean : rm - rf *.o prog
